package cn.xlink.telinkoffical.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.xlink.telinkoffical.bean.greenDao.User;
import cn.xlink.telinkoffical.bean.greenDao.PlaceSort;
import cn.xlink.telinkoffical.bean.greenDao.LightSort;
import cn.xlink.telinkoffical.bean.greenDao.GroupSort;
import cn.xlink.telinkoffical.bean.greenDao.SceneSort;
import cn.xlink.telinkoffical.bean.greenDao.SceneActionSort;
import cn.xlink.telinkoffical.bean.greenDao.SceneTimerSort;

import cn.xlink.telinkoffical.database.UserDao;
import cn.xlink.telinkoffical.database.PlaceSortDao;
import cn.xlink.telinkoffical.database.LightSortDao;
import cn.xlink.telinkoffical.database.GroupSortDao;
import cn.xlink.telinkoffical.database.SceneSortDao;
import cn.xlink.telinkoffical.database.SceneActionSortDao;
import cn.xlink.telinkoffical.database.SceneTimerSortDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig placeSortDaoConfig;
    private final DaoConfig lightSortDaoConfig;
    private final DaoConfig groupSortDaoConfig;
    private final DaoConfig sceneSortDaoConfig;
    private final DaoConfig sceneActionSortDaoConfig;
    private final DaoConfig sceneTimerSortDaoConfig;

    private final UserDao userDao;
    private final PlaceSortDao placeSortDao;
    private final LightSortDao lightSortDao;
    private final GroupSortDao groupSortDao;
    private final SceneSortDao sceneSortDao;
    private final SceneActionSortDao sceneActionSortDao;
    private final SceneTimerSortDao sceneTimerSortDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        placeSortDaoConfig = daoConfigMap.get(PlaceSortDao.class).clone();
        placeSortDaoConfig.initIdentityScope(type);

        lightSortDaoConfig = daoConfigMap.get(LightSortDao.class).clone();
        lightSortDaoConfig.initIdentityScope(type);

        groupSortDaoConfig = daoConfigMap.get(GroupSortDao.class).clone();
        groupSortDaoConfig.initIdentityScope(type);

        sceneSortDaoConfig = daoConfigMap.get(SceneSortDao.class).clone();
        sceneSortDaoConfig.initIdentityScope(type);

        sceneActionSortDaoConfig = daoConfigMap.get(SceneActionSortDao.class).clone();
        sceneActionSortDaoConfig.initIdentityScope(type);

        sceneTimerSortDaoConfig = daoConfigMap.get(SceneTimerSortDao.class).clone();
        sceneTimerSortDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        placeSortDao = new PlaceSortDao(placeSortDaoConfig, this);
        lightSortDao = new LightSortDao(lightSortDaoConfig, this);
        groupSortDao = new GroupSortDao(groupSortDaoConfig, this);
        sceneSortDao = new SceneSortDao(sceneSortDaoConfig, this);
        sceneActionSortDao = new SceneActionSortDao(sceneActionSortDaoConfig, this);
        sceneTimerSortDao = new SceneTimerSortDao(sceneTimerSortDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(PlaceSort.class, placeSortDao);
        registerDao(LightSort.class, lightSortDao);
        registerDao(GroupSort.class, groupSortDao);
        registerDao(SceneSort.class, sceneSortDao);
        registerDao(SceneActionSort.class, sceneActionSortDao);
        registerDao(SceneTimerSort.class, sceneTimerSortDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        placeSortDaoConfig.getIdentityScope().clear();
        lightSortDaoConfig.getIdentityScope().clear();
        groupSortDaoConfig.getIdentityScope().clear();
        sceneSortDaoConfig.getIdentityScope().clear();
        sceneActionSortDaoConfig.getIdentityScope().clear();
        sceneTimerSortDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PlaceSortDao getPlaceSortDao() {
        return placeSortDao;
    }

    public LightSortDao getLightSortDao() {
        return lightSortDao;
    }

    public GroupSortDao getGroupSortDao() {
        return groupSortDao;
    }

    public SceneSortDao getSceneSortDao() {
        return sceneSortDao;
    }

    public SceneActionSortDao getSceneActionSortDao() {
        return sceneActionSortDao;
    }

    public SceneTimerSortDao getSceneTimerSortDao() {
        return sceneTimerSortDao;
    }

}
