package cn.xlink.telinkoffical.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.xlink.telinkoffical.bean.greenDao.SceneActionSort;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCENE_ACTION_SORT".
*/
public class SceneActionSortDao extends AbstractDao<SceneActionSort, Long> {

    public static final String TABLENAME = "SCENE_ACTION_SORT";

    /**
     * Properties of entity SceneActionSort.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SceneId = new Property(1, Integer.class, "sceneId", false, "SCENE_ID");
        public final static Property Brightness = new Property(2, Integer.class, "brightness", false, "BRIGHTNESS");
        public final static Property Temperature = new Property(3, Integer.class, "temperature", false, "TEMPERATURE");
        public final static Property Color = new Property(4, Integer.class, "color", false, "COLOR");
        public final static Property DeviceMesh = new Property(5, Integer.class, "deviceMesh", false, "DEVICE_MESH");
        public final static Property Type = new Property(6, String.class, "Type", false, "TYPE");
    };


    public SceneActionSortDao(DaoConfig config) {
        super(config);
    }
    
    public SceneActionSortDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCENE_ACTION_SORT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SCENE_ID\" INTEGER," + // 1: sceneId
                "\"BRIGHTNESS\" INTEGER," + // 2: brightness
                "\"TEMPERATURE\" INTEGER," + // 3: temperature
                "\"COLOR\" INTEGER," + // 4: color
                "\"DEVICE_MESH\" INTEGER," + // 5: deviceMesh
                "\"TYPE\" TEXT);"); // 6: Type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCENE_ACTION_SORT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SceneActionSort entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer sceneId = entity.getSceneId();
        if (sceneId != null) {
            stmt.bindLong(2, sceneId);
        }
 
        Integer brightness = entity.getBrightness();
        if (brightness != null) {
            stmt.bindLong(3, brightness);
        }
 
        Integer temperature = entity.getTemperature();
        if (temperature != null) {
            stmt.bindLong(4, temperature);
        }
 
        Integer color = entity.getColor();
        if (color != null) {
            stmt.bindLong(5, color);
        }
 
        Integer deviceMesh = entity.getDeviceMesh();
        if (deviceMesh != null) {
            stmt.bindLong(6, deviceMesh);
        }
 
        String Type = entity.getType();
        if (Type != null) {
            stmt.bindString(7, Type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SceneActionSort readEntity(Cursor cursor, int offset) {
        SceneActionSort entity = new SceneActionSort( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // sceneId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // brightness
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // temperature
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // color
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // deviceMesh
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // Type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SceneActionSort entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSceneId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setBrightness(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTemperature(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setColor(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDeviceMesh(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SceneActionSort entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SceneActionSort entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
