package cn.xlink.telinkoffical.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCENE_TIMER_SORT".
 */
public class SceneTimerSort {

    private Long id;
    private Integer sceneId;
    private Integer sceneTimerId;
    private Integer timerId;
    private Integer timerType;
    private Integer deviceMesh;
    private Integer hour;
    private Integer minute;
    private Integer workDay;
    private Boolean isEnable;
    private String Type;

    public SceneTimerSort() {
    }

    public SceneTimerSort(Long id) {
        this.id = id;
    }

    public SceneTimerSort(Long id, Integer sceneId, Integer sceneTimerId, Integer timerId, Integer timerType, Integer deviceMesh, Integer hour, Integer minute, Integer workDay, Boolean isEnable, String Type) {
        this.id = id;
        this.sceneId = sceneId;
        this.sceneTimerId = sceneTimerId;
        this.timerId = timerId;
        this.timerType = timerType;
        this.deviceMesh = deviceMesh;
        this.hour = hour;
        this.minute = minute;
        this.workDay = workDay;
        this.isEnable = isEnable;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSceneId() {
        return sceneId;
    }

    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    public Integer getSceneTimerId() {
        return sceneTimerId;
    }

    public void setSceneTimerId(Integer sceneTimerId) {
        this.sceneTimerId = sceneTimerId;
    }

    public Integer getTimerId() {
        return timerId;
    }

    public void setTimerId(Integer timerId) {
        this.timerId = timerId;
    }

    public Integer getTimerType() {
        return timerType;
    }

    public void setTimerType(Integer timerType) {
        this.timerType = timerType;
    }

    public Integer getDeviceMesh() {
        return deviceMesh;
    }

    public void setDeviceMesh(Integer deviceMesh) {
        this.deviceMesh = deviceMesh;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    public Integer getWorkDay() {
        return workDay;
    }

    public void setWorkDay(Integer workDay) {
        this.workDay = workDay;
    }

    public Boolean getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
