package com.jeff.dominatelight.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP_SORT".
 */
public class GroupSort {

    private Long id;
    private String name;
    private Integer meshAddress;
    private Integer brightness;
    private Integer color;
    private Integer temperature;
    private Boolean isShowOnHomeScreen;
    private String members;
    private String Type;

    public GroupSort() {
    }

    public GroupSort(Long id) {
        this.id = id;
    }

    public GroupSort(Long id, String name, Integer meshAddress, Integer brightness, Integer color, Integer temperature, Boolean isShowOnHomeScreen, String members, String Type) {
        this.id = id;
        this.name = name;
        this.meshAddress = meshAddress;
        this.brightness = brightness;
        this.color = color;
        this.temperature = temperature;
        this.isShowOnHomeScreen = isShowOnHomeScreen;
        this.members = members;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getMeshAddress() {
        return meshAddress;
    }

    public void setMeshAddress(Integer meshAddress) {
        this.meshAddress = meshAddress;
    }

    public Integer getBrightness() {
        return brightness;
    }

    public void setBrightness(Integer brightness) {
        this.brightness = brightness;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public Integer getTemperature() {
        return temperature;
    }

    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    public Boolean getIsShowOnHomeScreen() {
        return isShowOnHomeScreen;
    }

    public void setIsShowOnHomeScreen(Boolean isShowOnHomeScreen) {
        this.isShowOnHomeScreen = isShowOnHomeScreen;
    }

    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
