package com.jeff.dominatelight.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIGHT_SORT".
 */
public class LightSort {

    private Long id;
    private String name;
    private String macAddress;
    private String firmwareRevision;
    private Integer meshAddress;
    private Integer lightType;
    private Boolean isAlone;
    private Boolean isShowOnHomeScreen;
    private Boolean isAddToDefault;
    private String Type;

    public LightSort() {
    }

    public LightSort(Long id) {
        this.id = id;
    }

    public LightSort(Long id, String name, String macAddress, String firmwareRevision, Integer meshAddress, Integer lightType, Boolean isAlone, Boolean isShowOnHomeScreen, Boolean isAddToDefault, String Type) {
        this.id = id;
        this.name = name;
        this.macAddress = macAddress;
        this.firmwareRevision = firmwareRevision;
        this.meshAddress = meshAddress;
        this.lightType = lightType;
        this.isAlone = isAlone;
        this.isShowOnHomeScreen = isShowOnHomeScreen;
        this.isAddToDefault = isAddToDefault;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMacAddress() {
        return macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    public String getFirmwareRevision() {
        return firmwareRevision;
    }

    public void setFirmwareRevision(String firmwareRevision) {
        this.firmwareRevision = firmwareRevision;
    }

    public Integer getMeshAddress() {
        return meshAddress;
    }

    public void setMeshAddress(Integer meshAddress) {
        this.meshAddress = meshAddress;
    }

    public Integer getLightType() {
        return lightType;
    }

    public void setLightType(Integer lightType) {
        this.lightType = lightType;
    }

    public Boolean getIsAlone() {
        return isAlone;
    }

    public void setIsAlone(Boolean isAlone) {
        this.isAlone = isAlone;
    }

    public Boolean getIsShowOnHomeScreen() {
        return isShowOnHomeScreen;
    }

    public void setIsShowOnHomeScreen(Boolean isShowOnHomeScreen) {
        this.isShowOnHomeScreen = isShowOnHomeScreen;
    }

    public Boolean getIsAddToDefault() {
        return isAddToDefault;
    }

    public void setIsAddToDefault(Boolean isAddToDefault) {
        this.isAddToDefault = isAddToDefault;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
