package com.jeff.dominatelight.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLACE_SORT".
 */
public class PlaceSort {

    private Long id;
    private String name;
    private String meshAddress;
    private String meshKey;
    private String factoryName;
    private String factoryMeshKey;
    private String placeId;
    private String creatorAccount;
    private String creatorName;
    private String creatorId;
    private String createDate;
    private Long placeVersion;
    private String lastUseDate;
    private Integer deviceIdRecord;
    private Integer role;
    private String Type;

    public PlaceSort() {
    }

    public PlaceSort(Long id) {
        this.id = id;
    }

    public PlaceSort(Long id, String name, String meshAddress, String meshKey, String factoryName, String factoryMeshKey, String placeId, String creatorAccount, String creatorName, String creatorId, String createDate, Long placeVersion, String lastUseDate, Integer deviceIdRecord, Integer role, String Type) {
        this.id = id;
        this.name = name;
        this.meshAddress = meshAddress;
        this.meshKey = meshKey;
        this.factoryName = factoryName;
        this.factoryMeshKey = factoryMeshKey;
        this.placeId = placeId;
        this.creatorAccount = creatorAccount;
        this.creatorName = creatorName;
        this.creatorId = creatorId;
        this.createDate = createDate;
        this.placeVersion = placeVersion;
        this.lastUseDate = lastUseDate;
        this.deviceIdRecord = deviceIdRecord;
        this.role = role;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMeshAddress() {
        return meshAddress;
    }

    public void setMeshAddress(String meshAddress) {
        this.meshAddress = meshAddress;
    }

    public String getMeshKey() {
        return meshKey;
    }

    public void setMeshKey(String meshKey) {
        this.meshKey = meshKey;
    }

    public String getFactoryName() {
        return factoryName;
    }

    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    public String getFactoryMeshKey() {
        return factoryMeshKey;
    }

    public void setFactoryMeshKey(String factoryMeshKey) {
        this.factoryMeshKey = factoryMeshKey;
    }

    public String getPlaceId() {
        return placeId;
    }

    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    public String getCreatorAccount() {
        return creatorAccount;
    }

    public void setCreatorAccount(String creatorAccount) {
        this.creatorAccount = creatorAccount;
    }

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public String getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public Long getPlaceVersion() {
        return placeVersion;
    }

    public void setPlaceVersion(Long placeVersion) {
        this.placeVersion = placeVersion;
    }

    public String getLastUseDate() {
        return lastUseDate;
    }

    public void setLastUseDate(String lastUseDate) {
        this.lastUseDate = lastUseDate;
    }

    public Integer getDeviceIdRecord() {
        return deviceIdRecord;
    }

    public void setDeviceIdRecord(Integer deviceIdRecord) {
        this.deviceIdRecord = deviceIdRecord;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
