package cn.xlink.telinkoffical.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCENE_ACTION_SORT".
 */
public class SceneActionSort {

    private Long id;
    private Integer sceneId;
    private Integer brightness;
    private Integer temperature;
    private Integer color;
    private Integer deviceMesh;
    private String Type;

    public SceneActionSort() {
    }

    public SceneActionSort(Long id) {
        this.id = id;
    }

    public SceneActionSort(Long id, Integer sceneId, Integer brightness, Integer temperature, Integer color, Integer deviceMesh, String Type) {
        this.id = id;
        this.sceneId = sceneId;
        this.brightness = brightness;
        this.temperature = temperature;
        this.color = color;
        this.deviceMesh = deviceMesh;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSceneId() {
        return sceneId;
    }

    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    public Integer getBrightness() {
        return brightness;
    }

    public void setBrightness(Integer brightness) {
        this.brightness = brightness;
    }

    public Integer getTemperature() {
        return temperature;
    }

    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public Integer getDeviceMesh() {
        return deviceMesh;
    }

    public void setDeviceMesh(Integer deviceMesh) {
        this.deviceMesh = deviceMesh;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
