package cn.xlink.telinkoffical.bean.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String Account;
    private String Name;
    private String Password;
    private String Uid;
    private String AuthKey;
    private String RefreshToken;
    private String AccessToken;
    private Boolean isVaild;
    private String Type;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String Account, String Name, String Password, String Uid, String AuthKey, String RefreshToken, String AccessToken, Boolean isVaild, String Type) {
        this.id = id;
        this.Account = Account;
        this.Name = Name;
        this.Password = Password;
        this.Uid = Uid;
        this.AuthKey = AuthKey;
        this.RefreshToken = RefreshToken;
        this.AccessToken = AccessToken;
        this.isVaild = isVaild;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return Account;
    }

    public void setAccount(String Account) {
        this.Account = Account;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getUid() {
        return Uid;
    }

    public void setUid(String Uid) {
        this.Uid = Uid;
    }

    public String getAuthKey() {
        return AuthKey;
    }

    public void setAuthKey(String AuthKey) {
        this.AuthKey = AuthKey;
    }

    public String getRefreshToken() {
        return RefreshToken;
    }

    public void setRefreshToken(String RefreshToken) {
        this.RefreshToken = RefreshToken;
    }

    public String getAccessToken() {
        return AccessToken;
    }

    public void setAccessToken(String AccessToken) {
        this.AccessToken = AccessToken;
    }

    public Boolean getIsVaild() {
        return isVaild;
    }

    public void setIsVaild(Boolean isVaild) {
        this.isVaild = isVaild;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
